"""The manager's dialog must fit inside MO2 and let the user narrow it (the owner, 2026-10-05: "the mm plugins popup
window is wider than mo2 and wont let me adjust its width"). A label that does not wrap is as wide as its whole text,
and the dialog cannot be made narrower than its widest child - so every long label must wrap and every row must fit.

Builds the dialog offscreen on a small scratch instance, prints its minimum width and the widest children, and fails
when the minimum is wider than LIMIT.

    python tools\\check_dialog_width.py        exit 0 = the dialog can be narrowed to LIMIT px or less
"""
import importlib.util, os, shutil, sys, tempfile, types

LIMIT = 760   # well inside MO2's own window at 1280 px; the dialog opens larger and is resized freely down to this

# Windows: Qt's real platform, so labels and buttons are measured in the fonts MO2 draws with (the offscreen
# platform has no system fonts and measures everything far wider). The dialog is never shown.
os.environ["QT_QPA_PLATFORM"] = "windows" if sys.platform == "win32" else "offscreen"
stub = types.ModuleType("mobase")
stub.__getattr__ = lambda n: type(n, (object,), {"__init__": lambda self, *a, **k: None})
sys.modules["mobase"] = stub
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec = importlib.util.spec_from_file_location("mm", os.path.join(HERE, "MO2ModlistManager.py"))
mm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mm)
from PyQt6.QtWidgets import QApplication, QWidget

root = tempfile.mkdtemp(prefix="mm-width-")
try:
    inst = os.path.join(root, "Mo2")
    prof = os.path.join(inst, "profiles", "Test")
    mods = os.path.join(inst, "mods")
    os.makedirs(prof)
    for m in ("SkyUI", "SmoothCam"):
        os.makedirs(os.path.join(mods, m))
        open(os.path.join(mods, m, "meta.ini"), "w").write("[General]\nmodid=0\n")
    open(os.path.join(prof, "modlist.txt"), "w", newline="\r\n").write("# This file was automatically generated by Mod Organizer.\n+SkyUI\n+SmoothCam\n")
    app = QApplication([])
    app.setProperty("dataPath", inst.replace("\\", "/"))

    class Org:
        def basePath(self): return inst.replace("\\", "/")
        def modsPath(self): return mods.replace("\\", "/")
        def profilePath(self): return prof.replace("\\", "/")
        def profileName(self): return "Test"
        def refresh(self, save=True): pass
        def managedGame(self): raise RuntimeError("no game in the test")
        def pluginSetting(self, plugin, key): return None

    p = mm.MO2ModlistManager()
    p._organizer = Org()
    p._log = lambda msg: None
    dlg = mm.RulerDialog(p)
    dlg.compute()
    dlg.ensurePolished()
    need = dlg.minimumSizeHint().width()
    print(f"dialog: opens {dlg.width()} px wide, can be narrowed to {need} px (limit {LIMIT})")
    widest = sorted(((w.minimumSizeHint().width(), type(w).__name__, (getattr(w, "text", lambda: "")() or "")[:70])
                     for w in dlg.findChildren(QWidget)), reverse=True)[:6]
    for width, kind, text in widest:
        print(f"  {width:5d}  {kind:14s} {text}")
    if "--detail" in sys.argv:              # each tab page, and each row of widgets with what it holds
        from PyQt6.QtWidgets import QHBoxLayout
        for i in range(dlg.tabs.count()):
            print(f"  tab {dlg.tabs.tabText(i):24s} {dlg.tabs.widget(i).minimumSizeHint().width()}")
        for lay in dlg.findChildren(QHBoxLayout):
            parts = [f"{type(w).__name__}({(getattr(w, 'text', lambda: '')() or '')[:20]})={w.minimumSizeHint().width()}"
                     for w in (lay.itemAt(j).widget() for j in range(lay.count())) if w is not None]
            print(f"  row {lay.minimumSize().width():5d}: " + ", ".join(parts))
    ok = need <= LIMIT
finally:
    shutil.rmtree(root, ignore_errors=True)
print("PASS" if ok else "FAIL - the dialog cannot be narrowed enough")
sys.exit(0 if ok else 1)
