"""The Modlist Manager's proposed order must pass the launch audit (2026-09-24).

For each Njordlinger profile: run the offline dry run, write its proposed pane and plugin order into a temporary profile
(_mm-selfcheck), run .MD\\scripts\\nj-order-audit.py on it, remove the temporary profile. Exit 1 when the audit FAILs on
anything the real apply would not fix itself. The one known difference: plugins the plan parks in Optional ESPs are
still in their mod folders here (the dry run moves no files), so a "missing from plugins.txt" FAIL that lists exactly
those plugins is expected and not counted.

Why: on 2026-09-23/24 an apply on the Test profile put a 1.5 port below the AE build of its DLL, and the main-profile
plan put PGPatcher's PG_1.esp after DynDOLOD.esp - both launch-audit FAILs, both found only after the order was
written. Gate rule modlist-manager-order-passes-the-launch-audit runs this before the plugin is packaged.

    python tools\\selfcheck.py [--instance D:\\Modlists\\Njordlinger] [--profiles "Njordlinger Test,Njordlinger"] [--cache DIR]
"""
import json, os, re, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIT = r"D:\Claude output\.MD\scripts\nj-order-audit.py"
args = sys.argv[1:]
def opt(k, d):
    return args[args.index(k) + 1] if k in args else d
inst = opt("--instance", r"D:\Modlists\Njordlinger")
profiles = [p.strip() for p in opt("--profiles", "Njordlinger Test,Njordlinger").split(",") if p.strip()]
cache_root = opt("--cache", os.path.join(tempfile.gettempdir(), "mm-selfcheck"))
os.makedirs(cache_root, exist_ok=True)

bad_total = 0
for prof in profiles:
    cache = os.path.join(cache_root, re.sub(r"\W+", "-", prof))
    os.makedirs(cache, exist_ok=True)
    r = subprocess.run([sys.executable, os.path.join(HERE, "MO2ModlistManager.py"), inst, prof, cache], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"FAIL  {prof}: the dry run failed\n{r.stdout[-800:]}{r.stderr[-800:]}"); bad_total += 1; continue
    d = json.load(open(os.path.join(cache, "dry-run.json"), encoding="utf-8"))
    parked = {x[0].lower() for x in d.get("plugin_state", {}).get("to_optional", [])}

    tmp = os.path.join(inst, "profiles", "_mm-selfcheck")
    if os.path.exists(tmp): shutil.rmtree(tmp)
    shutil.copytree(os.path.join(inst, "profiles", prof), tmp, ignore=shutil.ignore_patterns("saves", "*.bak*"))
    try:
        with open(os.path.join(tmp, "modlist.txt"), "w", encoding="utf-8", newline="\n") as f:
            f.write("# This file was automatically generated by Mod Organizer.\n")
            for name, on in reversed(d["rows"]):
                f.write(("+" if on else "-") + name + "\n")
        enabled = {l.strip()[1:].lower() for l in open(os.path.join(inst, "profiles", prof, "plugins.txt"), encoding="utf-8", errors="replace") if l.startswith("*")}
        enabled |= {x[0].lower() for x in d.get("plugin_state", {}).get("activate", [])}
        enabled |= {x[0].lower() for x in d.get("plugin_state", {}).get("from_optional", [])}
        with open(os.path.join(tmp, "plugins.txt"), "w", encoding="utf-8", newline="\r\n") as f:
            f.write("# This file was automatically generated by Mod Organizer.\n")
            for p in d["plugins"]:
                f.write(("*" if p.lower() in enabled else "") + p + "\n")
        with open(os.path.join(tmp, "loadorder.txt"), "w", encoding="utf-8", newline="\r\n") as f:
            f.write("# This file was automatically generated by Mod Organizer.\n" + "".join(p + "\n" for p in d["plugins"]))
        a = subprocess.run([sys.executable, AUDIT, "_mm-selfcheck"], capture_output=True, text=True)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    fails = []
    for line in a.stdout.splitlines():
        if not line.startswith("FAIL"):
            continue
        m = re.match(r"FAIL\s+\d+ plugin\(s\) of enabled mods missing from plugins\.txt: (.*)", line)
        if m and {x.strip() for x in m.group(1).split(";")} <= parked:
            continue          # parked in Optional ESPs by the real apply
        fails.append(line)
    ex = d.get("facts", {}).get("expectations", [])
    missed = [e for e in ex if not e[3]]
    status = "PASS" if not fails and not missed else "FAIL"
    print(f"{status}  {prof}: {len(ex) - len(missed)}/{len(ex)} rulings met, launch audit {'clean' if not fails else str(len(fails)) + ' FAIL(s)'}")
    for f in fails: print("      ", f[:220])
    for e in missed: print(f"       ruling missed: {e[0]} wanted {e[1]} got {e[2]}")
    bad_total += status == "FAIL"

sys.exit(1 if bad_total else 0)
