"""An instance whose profiles and mods are NOT under its base folder (1.1.2, the Nexus report of 2026-09-29: profiles in
Mo2/SSE/profiles gave "No such file or directory: 'C:/Mo2/profiles/Test/modlist.txt'").

Two parts, both on a scratch instance built here and removed after:
  1. the offline resolver - ModOrganizer.ini's profiles_directory / mod_directory with %BASE_DIR% (MO2's PathSettings);
  2. the plugin class itself under PyQt6 offscreen, with an organizer that answers the way MO2 does for that layout
     (basePath = the base, modsPath / profilePath = the configured folders, the application's dataPath property):
     compute(), rules(), and the restore list must all read the configured folders.

    python tools\\test_custom_dirs.py        exit 0 = every check passed
"""
import importlib.util, os, shutil, sys, tempfile, types

os.environ["QT_QPA_PLATFORM"] = "offscreen"
stub = types.ModuleType("mobase")
stub.__getattr__ = lambda n: type(n, (object,), {"__init__": lambda self, *a, **k: None})
sys.modules["mobase"] = stub
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec = importlib.util.spec_from_file_location("mm", os.path.join(HERE, "MO2ModlistManager.py"))
mm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mm)
from PyQt6.QtWidgets import QApplication

bad = 0


def ok(cond, what):
    global bad
    print(("PASS " if cond else "FAIL ") + what)
    bad += 0 if cond else 1


root = tempfile.mkdtemp(prefix="mm-customdirs-")
try:
    inst = os.path.join(root, "Mo2")
    prof = os.path.join(inst, "SSE", "profiles", "Test")
    mods = os.path.join(inst, "SSE", "mods")
    os.makedirs(prof)
    for m in ("SkyUI", "USSEP"):
        os.makedirs(os.path.join(mods, m))
        open(os.path.join(mods, m, "meta.ini"), "w").write("[General]\nmodid=0\n")
    open(os.path.join(mods, "USSEP", "Unofficial Skyrim Special Edition Patch.esp"), "wb").write(b"TES4")
    open(os.path.join(inst, "ModOrganizer.ini"), "w").write(
        "[General]\ngameName=Skyrim Special Edition\n\n[Settings]\n"
        "profiles_directory=%BASE_DIR%/SSE/profiles\nmod_directory=%BASE_DIR%/SSE/mods\n")
    open(os.path.join(prof, "modlist.txt"), "w", newline="\r\n").write(
        "# This file was automatically generated by Mod Organizer.\n+SkyUI\n+USSEP\n")
    open(os.path.join(prof, "plugins.txt"), "w", newline="\r\n").write(
        "# This file was automatically generated by Mod Organizer.\n*Unofficial Skyrim Special Edition Patch.esp\n")

    # 1. offline resolver
    i = mm.instance_from_dir(inst)
    ok(os.path.normcase(i.profiles) == os.path.normcase(os.path.join(inst, "SSE", "profiles")), f"profiles_directory resolved: {i.profiles}")
    ok(os.path.normcase(i.mods) == os.path.normcase(mods), f"mod_directory resolved: {i.mods}")
    d = mm.instance_from_dir(os.path.join(root, "plain"))
    ok(d.profiles == os.path.join(os.path.normpath(os.path.join(root, "plain")), "profiles"), "no ini: profiles under the base, as MO2's default")

    # 2. the plugin class, the way MO2 hands it the folders
    app = QApplication([])
    app.setProperty("dataPath", inst.replace("\\", "/"))

    class Org:
        def basePath(self): return inst.replace("\\", "/")
        def modsPath(self): return mods.replace("\\", "/")
        def profilePath(self): return prof.replace("\\", "/")
        def profileName(self): return "Test"
        def refresh(self, save=True): pass
        def managedGame(self): raise RuntimeError("no game in the test")
        def pluginSetting(self, plugin, key): return None

    p = mm.MO2ModlistManager()
    p._organizer = Org()
    got = p._instance()
    ok(os.path.normcase(got.profiles) == os.path.normcase(os.path.dirname(prof)) and os.path.normcase(got.mods) == os.path.normcase(mods),
       f"the plugin takes MO2's own folders: {got}")
    res = p.compute()
    ok(os.path.normcase(res["modlist_path"]) == os.path.normcase(os.path.join(prof, "modlist.txt")), f"compute() read {res['modlist_path']}")
    ok(os.path.normcase(res["mods_dir"]) == os.path.normcase(mods), f"compute() scanned {res['mods_dir']}")
    ok(isinstance(p.rules(), dict), "rules() reads the profile's rules file from profilePath")
    cache = os.path.join(root, "cache")
    ok(mm.list_backups(cache, got) == [], "the restore list opens (no backups yet) on the configured profiles folder")
    before = open(os.path.join(prof, "modlist.txt"), encoding="utf-8-sig").read()
    backup = mm.apply(res, got, "Test", cache)
    ok(os.path.isfile(os.path.join(backup, "modlist.txt")) and open(os.path.join(backup, "modlist.txt"), encoding="utf-8-sig").read() == before,
       "Apply backed up the configured profile's modlist.txt")
    ok(not os.path.exists(os.path.join(inst, "profiles")), "Apply wrote nothing to <base>/profiles")
    listed = mm.list_backups(cache, got)
    ok(len(listed) == 1 and listed[0][2] == "Test", f"the restore list shows that backup for Test: {listed}")
finally:
    shutil.rmtree(root, ignore_errors=True)
print("ALL PASS" if not bad else f"{bad} FAILED")
sys.exit(1 if bad else 0)
