"""Learned pins (1.1.3; the owner, 2026-10-05: "any mods that the user shifts to a different separator becomes a new rule
automatically so they don't have to make them one by one manually").

On a scratch instance built here and removed after, through the plugin class under PyQt6 offscreen (compute() keeps what
it learns, as in MO2) and the real apply() / restore_backup():
  A  first Apply records where it put every mod (auto_placement)
  B  a run with nothing moved learns nothing
  C  a mod moved by hand to another category separator is learned, kept in the rules file, and planned there
  D  after the next Apply it stays there, and a further run changes nothing
  E  moved back to where the manager had it, the learned pin is forgotten and the evidence places it again
  F  a separator of the user's own naming teaches nothing
  G  a pin the user typed wins: no learning for that mod
  H  Forget learned rules: the pin goes and the move is not learned again
  I  the switch off: nothing learned
  J  Restore backup puts back the learned pins and recorded places the backup holds
  K  the dialog's Rules tab: learned rows listed, Remove selected, Forget learned rules

    python tools\\test_learned_pins.py        exit 0 = every check passed
"""
import importlib.util, os, shutil, sys, tempfile, types

os.environ["QT_QPA_PLATFORM"] = "offscreen"
stub = types.ModuleType("mobase")
stub.__getattr__ = lambda n: type(n, (object,), {"__init__": lambda self, *a, **k: None})
sys.modules["mobase"] = stub
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec = importlib.util.spec_from_file_location("mm", os.path.join(HERE, "MO2ModlistManager.py"))
mm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mm)
from PyQt6.QtWidgets import QApplication

bad = 0


def ok(cond, what):
    global bad
    print(("PASS " if cond else "FAIL ") + what)
    bad += 0 if cond else 1


MODS = sys.argv[1:] or ["SkyUI", "RaceMenu", "SmoothCam", "Immersive Armors", "Lux", "Campfire", "Precision", "Immersive Sounds - Compendium"]
PROBE = os.environ.get("MM_PROBE") == "1"     # MM_PROBE=1: print where each mod lands and stop

root = tempfile.mkdtemp(prefix="mm-learned-")
try:
    inst = os.path.join(root, "Mo2")
    prof = os.path.join(inst, "profiles", "Test")
    mods = os.path.join(inst, "mods")
    cache = os.path.join(root, "cache")
    os.makedirs(prof)
    for m in MODS:
        os.makedirs(os.path.join(mods, m))
        open(os.path.join(mods, m, "meta.ini"), "w").write("[General]\nmodid=0\n")
    open(os.path.join(inst, "ModOrganizer.ini"), "w").write("[General]\ngameName=Skyrim Special Edition\n")
    ml = os.path.join(prof, "modlist.txt")
    open(ml, "w", newline="\r\n").write("# This file was automatically generated by Mod Organizer.\n" + "".join(f"+{m}\n" for m in MODS))

    app = QApplication([])
    app.setProperty("dataPath", inst.replace("\\", "/"))

    class Org:
        settings = {}
        def basePath(self): return inst.replace("\\", "/")
        def modsPath(self): return mods.replace("\\", "/")
        def profilePath(self): return prof.replace("\\", "/")
        def profileName(self): return "Test"
        def refresh(self, save=True): pass
        def managedGame(self): raise RuntimeError("no game in the test")
        def pluginSetting(self, plugin, key): return Org.settings.get(key)

    p = mm.MO2ModlistManager()
    p._organizer = Org()
    log = []
    p._log = lambda msg: log.append(msg)

    def placed(res, mod):
        return mm.separator_of(res["rows"]).get(mod)

    def move(mod, under_sep):
        """Move a mod in modlist.txt to just under a separator, as a drag in MO2's pane would."""
        rows, header = mm.read_modlist(ml)
        row = next(r for r in rows if r[0] == mod)
        rows.remove(row)
        at = next(i for i, r in enumerate(rows) if r[0].lower() == under_sep.lower())
        rows.insert(at + 1, row)
        mm.write_modlist(ml, rows, header)

    # ---- A: the first Apply ------------------------------------------------------------------------------------------
    res = p.compute()
    if PROBE:
        for m in MODS:
            mod = next(x for x in res["mods"] if x.name == m)
            print(f"{m:34s} -> {mod.category:40s} under {placed(res, m)}")
        raise SystemExit(0)
    home = {m: placed(res, m) for m in MODS}
    ui_sep, cam_sep = home["SkyUI"], home["SmoothCam"]
    ok(ui_sep and cam_sep and ui_sep != cam_sep and ui_sep.lower() in mm.LEARNABLE and cam_sep.lower() in mm.LEARNABLE,
       f"SkyUI and SmoothCam are planned under two category separators: {ui_sep} / {cam_sep}")
    mm.apply(res, p._instance(), "Test", cache)
    r = p.rules()
    ok(r.get("auto_placement", {}).get("SkyUI") == ui_sep, f"A  Apply recorded where it put SkyUI: {r.get('auto_placement', {}).get('SkyUI')}")

    # ---- B: nothing moved ---------------------------------------------------------------------------------------------
    res = p.compute()
    ok(not res["learned_changes"] and not res["learned"], f"B  nothing moved, nothing learned: {res['learned_changes']}")

    # ---- C: moved by hand --------------------------------------------------------------------------------------------
    log.clear()
    move("SkyUI", cam_sep)
    res = p.compute()
    cam = mm.LEARNABLE[cam_sep.lower()]
    ui = mm.LEARNABLE[ui_sep.lower()]
    ok([c[:2] for c in res["learned_changes"]] == [("SkyUI", "learned")], f"C  the move is learned: {res['learned_changes']}")
    ok(p.rules().get("learned_pins", {}).get("SkyUI", {}).get("category") == cam, "C  compute() kept it in the rules file")
    ok(placed(res, "SkyUI") == cam_sep, f"C  the plan leaves SkyUI where it was moved: {placed(res, 'SkyUI')}")
    sky = next(x for x in res["mods"] if x.name == "SkyUI")
    ok(sky.why.startswith("pinned: learned") and ui in sky.why, f"C  the Placement tab says why: {sky.why}")
    ok(any(l == f"learned 'SkyUI' -> {cam} (moved there by hand; the manager had it in {ui})" for l in log), f"C  logged: {log[-1:]}")

    # ---- D: Apply, then a run changes nothing --------------------------------------------------------------------------
    backup_d = mm.apply(res, p._instance(), "Test", cache)
    res = p.compute()
    ok(not res["learned_changes"] and placed(res, "SkyUI") == cam_sep and not [x for x in res["moves"] if x[0] == "SkyUI"],
       f"D  after Apply it stays and nothing changes: {res['learned_changes']}")

    # ---- E: moved back ---------------------------------------------------------------------------------------------------
    log.clear()
    move("SkyUI", ui_sep)
    res = p.compute()
    ok([c[:2] for c in res["learned_changes"]] == [("SkyUI", "forgotten")], f"E  moved back: forgotten {res['learned_changes']}")
    ok("SkyUI" not in p.rules().get("learned_pins", {}) and placed(res, "SkyUI") == ui_sep, "E  gone from the rules file; the evidence places it")
    mm.apply(res, p._instance(), "Test", cache)

    # ---- F: a separator of the user's own naming ------------------------------------------------------------------------
    os.makedirs(os.path.join(mods, "My Favourites_separator"))
    open(os.path.join(mods, "My Favourites_separator", "meta.ini"), "w").write("[General]\nmodid=0\n")
    rows, header = mm.read_modlist(ml)
    rows.append(("My Favourites_separator", False))
    mm.write_modlist(ml, rows, header)
    move("SkyUI", "My Favourites_separator")
    res = p.compute()
    ok(not res["learned_changes"], f"F  a separator the user named teaches nothing: {res['learned_changes']}")
    move("SkyUI", ui_sep)

    # ---- G: a typed pin wins -------------------------------------------------------------------------------------------
    r = p.rules()
    r.setdefault("pins", {})["SkyUI"] = ui
    p.save_rules(r)
    move("SkyUI", cam_sep)
    res = p.compute()
    ok(not res["learned_changes"] and placed(res, "SkyUI") == ui_sep, f"G  a typed pin wins, nothing learned: {res['learned_changes']}")
    r = p.rules()
    r["pins"].pop("SkyUI")
    p.save_rules(r)

    # ---- H: Forget learned rules -------------------------------------------------------------------------------------
    res = p.compute()                      # SkyUI is still under the camera separator: learned now
    ok([c[:2] for c in res["learned_changes"]] == [("SkyUI", "learned")], "H  learned again once the typed pin is gone")
    r = p.rules()
    gone = mm.forget_learned(r)
    p.save_rules(r)
    res = p.compute()
    ok(gone == ["SkyUI"] and not res["learned_changes"] and not res["learned"] and placed(res, "SkyUI") == ui_sep,
       f"H  forgotten, not learned again, placed by its evidence: {res['learned_changes']} / {placed(res, 'SkyUI')}")
    mm.apply(res, p._instance(), "Test", cache)

    # ---- I: switched off -----------------------------------------------------------------------------------------------
    Org.settings["learn_from_moves"] = False
    move("SkyUI", cam_sep)
    res = p.compute()
    ok(not res["learned_changes"] and not p.rules().get("learned_pins"), f"I  switched off: nothing learned {res['learned_changes']}")
    Org.settings.clear()

    # ---- J: Restore backup -----------------------------------------------------------------------------------------------
    res = p.compute()                      # on again: learned
    ok([c[:2] for c in res["learned_changes"]] == [("SkyUI", "learned")], "J  learned with the switch back on")
    backup_j = mm.apply(res, p._instance(), "Test", cache)
    ok("SkyUI" in p.rules().get("learned_pins", {}), "J  that Apply kept the learned pin")
    import json
    held = json.load(open(os.path.join(backup_j, mm.RULES_FILE), encoding="utf-8"))
    r = p.rules()
    r["learned_pins"] = {}                 # something different now, so the restore has to put the backup's back
    p.save_rules(r)
    mm.restore_backup(backup_j, p._instance(), "Test", cache)
    r = p.rules()
    # compute() kept the pin when it saw the move, before that Apply: the backup holds it, with the list that has the move
    ok(r.get("learned_pins") == held.get("learned_pins") and "SkyUI" in r["learned_pins"],
       f"J  Restore puts back the learned pins the backup holds: {sorted(r.get('learned_pins', {}))}")
    ok(r.get("auto_placement", {}).get("SkyUI") == ui_sep, f"J  and where the Apply before it had put SkyUI: {r.get('auto_placement', {}).get('SkyUI')}")
    res = p.compute()
    ok(not res["learned_changes"] and placed(res, "SkyUI") == cam_sep, f"J  after the restore the list and the rules agree: {res['learned_changes']}")

    # ---- K: the dialog's Rules tab ------------------------------------------------------------------------------------
    move("Lux", cam_sep)                   # a second learned pin, so Remove selected and Forget each have one to take
    dlg = mm.RulerDialog(p)
    dlg.compute()
    rows = dlg._rules_rows()
    learned_rows = [r_ for r_ in rows if r_[0] == "pin (learned)"]
    ok(sorted(r_[1] for r_ in learned_rows) == ["Lux", "SkyUI"] and all(r_[2].startswith("Camera (the manager had it in") for r_ in learned_rows),
       f"K  the Rules tab lists both learned pins: {learned_rows}")
    i = next(n for n, r_ in enumerate(rows) if r_[:2] == ("pin (learned)", "Lux"))
    dlg.t_rules.selectRow(i)
    dlg._rule_del()
    r = p.rules()
    ok("Lux" not in r.get("learned_pins", {}) and "SkyUI" in r.get("learned_pins", {}) and str(r["auto_placement"].get("Lux", "")).lower() == cam_sep.lower(),
       "K  Remove selected forgets that one and records where it sits, so it is not learned again")
    mm.QMessageBox.question = staticmethod(lambda *a, **k: mm.QMessageBox.StandardButton.Yes)
    dlg._rule_forget_learned()
    ok(not p.rules().get("learned_pins") and not [r_ for r_ in dlg._rules_rows() if r_[0] == "pin (learned)"],
       "K  Forget learned rules empties them and the tab")
    res = p.compute()
    ok(not res["learned_changes"], f"K  nothing is learned again after forgetting: {res['learned_changes']}")
finally:
    shutil.rmtree(root, ignore_errors=True)
print("ALL PASS" if not bad else f"{bad} FAILED")
sys.exit(1 if bad else 0)
